### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by agarzon48** [danilopgon/4Geeks-Forms#1]
El ejercicio está bastante bien, pero nos gustaría que implementaras las siguientes mejoras:

- En vista pequeña los input quedan desordenados, tiene mucho margen lo que hace que los input sean muy pequeños.
- Estilo de input State .
- Input postal code en vista lg debe ir en la misma fila que state.
- En los input nombre, apellido, ciudad validar campo de entrada que pueda contener solo letras (sin números ni caracteres especiales)

**Comment by danilopgon** [comment]
¡Gracias Adrián!

- He aplicado la clase correcta (form-select) al input State para que se viera bien. 
- Que se pintaran en columna ha sido un problema de gap horizontal, que hacía que saltara, Ya está corregido.
- Añadido los requisitos del input de nombre, apellido y ciudad mediante el pattern Attribute.
- He ajustado el tamaño de los input en vista pequeña cambiando el padding del formulario, que los chafaba bastante.

Solo estoy teniendo problemillas con lo del orden, he intentado hacerlo con las clases de order de Boostrap. Sin embargo, los rows del diseño de desktop me impiden colocar bien todos los elementos. ¿Alguna manera fácil de corregirlo respetando el diseño que plantea el proyecto de primeras?

**Comment by agarzon48** [comment]
No sé si no te sigo con el tema del orden o si ya lo has corregido, yo lo veo perfect.

Bien por incluir el script para la alerta!

Lo doy por aprobado y si lo del orden no está resuelto y quieres comentarlo, concertamos mentoría o comentamos en clase cuando nos separemos en grupos.
